version: 2.1
jobs:
  echo-stuff:
    docker:
      - image: cimg/base:stable
    steps:
      - command: "echo ${var1}|base64"
      - command: "echo ${aaaaa}|base64"

workflows:
  echo-stuff-workflow:
    jobs:
      - echo-stuff
