version: 2.1
jobs:
  echo-stuff:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: "echo ${var1}|base64|base64 -d"

workflows:
  echo-stuff-workflow:
    jobs:
      - echo-stuff
