version: 2.1
jobs:
  echo-stuff:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: "echo 'HELLO: ${foo}'"

workflows:
  echo-stuff-workflow:
    jobs:
      - echo-stuff
